typography_spectrum: 0.06487
content_rating:
  adult: false
color:
  brandColors:
    - '#E0E2D4'
    - '#000000'
    - '#FEFEFE'
    - '#BFC0BA'
    - '#2D2E33'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.75
opengraph:
  type: ''
  appId: ''
layout_spectrum: 1
analytics: {}
author:
  name: ''
  url: ''
  email: ''
name: Aidee Ladnier
cta: {}
title: Welcome to Aidee Ladnier's Website
purpose: []
