analytics: {}
color:
  brandColors:
    - '#E0E2D4'
    - '#000000'
    - '#FEFEFE'
    - '#BFC0BA'
    - '#2D2E33'
  brandStrength: 1
  lightness: 0.8125
  rhythmicContrast: 0.75
  saturation: 0.1875
cta: {}
layout_spectrum: 1
name: Aidee Ladnier
opengraph: {}
purpose: []
typography_spectrum: 0.06487
