name: Aidee Ladnier
layout_spectrum: 1
typography_spectrum: 0.06487
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#E0E2D4'
    - '#000000'
    - '#FEFEFE'
    - '#BFC0BA'
    - '#2D2E33'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
title: 'because quirky characters fall in  love, too...'
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
