name: Aidee Ladnier
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06487
title: 'because quirky characters fall in love, too...'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2e2d6'
    - '#000000'
    - '#2b2f2e'
    - '#aa0233'
    - '#fe224d'
  brandStrength: 1
  lightness: 0.8153894741553813
  saturation: 0.5761639107950032
  rhythmicContrast: 0.32811777852475643
purpose: []
